name: Flatpak

on:
  push:
  pull_request:
  schedule:
    - cron: '45 21 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Submodules
        run: git submodule update --init --recursive

      - name: Install flatpak
        run: |
          sudo apt-get update
          sudo apt-get -y install flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Prepare environment
        run: |
          SHELL_VERSION=$(git grep -hoP '^\s*VERSION\s*=\s*\K.*$' HEAD -- stremio.pro)
          FLATPAK_PATH="Stremio $SHELL_VERSION.flatpak"
          node -e 'process.stdout.write("CURRENT_BRANCH="+process.env.GITHUB_REF.replace(/^refs\/(heads|tags)\//, "")+"\n")' >> $GITHUB_ENV
          echo SHELL_VERSION=$SHELL_VERSION >> $GITHUB_ENV
          echo FLATPAK_PATH=$FLATPAK_PATH >> $GITHUB_ENV
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then echo DEPLOY=false >> $GITHUB_ENV; else echo DEPLOY=true >> $GITHUB_ENV; fi

      - name: Build
        run: sudo flatpak-builder --repo=stremio-flatpak-repo --install-deps-from=flathub --force-clean _build com.stremio.Stremio.json

      - name: Pack
        run: |
          flatpak build-bundle stremio-flatpak-repo Stremio.flatpak com.stremio.Stremio beta
          mv Stremio.flatpak "$FLATPAK_PATH"

      - name: Store the Flatpak
        uses: actions/upload-artifact@v4
        with:
          name: StremioFlatpak
          path: ${{ env.FLATPAK_PATH }}

      
      
        if: ${{ !github.event.pull_request }}
